# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=7002
# ?????????????? ???????? ?????? ?? ?????? ????????? (????? 1 ? 2 ???????)
spring.jpa.hibernate.ddl-auto=update
# ????????? ?????? SQL-??????? ? ??????? (??????? ??? ??????? N+1)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Enable DishService cache hit/miss logs
logging.level.com.example.demo.service.DishService=DEBUG
logging.level.com.example.demo.aop.ServiceExecutionLoggingAspect=INFO
logging.level.com.example.demo.exception.GlobalExceptionHandler=WARN

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
